module.exports = [
  require('./critic.js'),
  require('./exec.js'),
  require('./grouping.js'),            
  require('./metadata.js'),            
  require('./scripting.js'),           
  require('./tabular.js'),             
  require('./textLevelSemantics.js'),  
  require('./embedded.js'),            
  require('./forms.js'),               
  require('./interactive.js'),         
  require('./rules.js'),               
  require('./sections.js'),            
  require('./text.js'),                
]
